### ISSUE TITLE
Upload request cancelled 

### ISSUE THREAD

**Issue by lnwdr** [DracoBlue/iasur#2]
Used Versions:

- Iasur 1.1.0
- Node 6.9.2
- NPM 3.10.9
- macOS 10.12.6
- Chrome 59.0.3071.115 (stable)

When trying to upload a file (both ZIP and other), the POST request get's cancelled before transmitting anything to the server:

<img width="654" alt="screen shot 2017-08-06 at 14 28 36" src="https://user-images.githubusercontent.com/1770511/29003249-95ef8920-7ab3-11e7-90a7-776e3ffe762e.png">

Meanwhile the server does't log anything: 

<img width="840" alt="screen shot 2017-08-06 at 14 31 43" src="https://user-images.githubusercontent.com/1770511/29003273-0d3ce4f0-7ab4-11e7-8e0c-835826027ac1.png">

**Comment by DracoBlue** [comment]
Hello @lnwdr ,

thanks for your bug report.

This was due to the fact, that your launched without the trailing slash

``` bash
$ iasur serve http://127.0.0.1:1337
```

and not with the trailing slash:

``` bash
$ iasur serve http://127.0.0.1:1337
```

I fixed this issue in iasur 1.2.0 (released some seconds ago), so both ways work now!

Best regards

Jan
